export enum ActionTypes {
    // Status
    LOADED = "LOADED",
    NOT_LOADED = "NOT_LOADED",
    IS_LOADING = "IS_LOADING",
    LOADING_FAILED = "LOADING_FAILED",

    // Fetch featured jobs
    FETCH_JOBS_LOADING = "FETCH_JOBS_LOADING",
    FETCH_JOBS = "FETCH_JOBS",
    FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS",
    FETCH_JOBS_ERROR = "FETCH_JOBS_ERROR",
}